exclude: ^docs/.*$
repos:
  - repo: local
    hooks:
      - id: ruff-check-fix
        name: ruff check --fix
        entry: uv run --group dev ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: uv run --group dev ruff format
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run --group dev mypy --config-file pyproject.toml maxpylang
        language: system
        pass_filenames: false
        types: [python]
      - id: prettier
        name: prettier --write
        entry: prettier --write
        language: node
        additional_dependencies: [prettier@3.8.1]
        types_or: [markdown, yaml]
